#!/usr/bin/env bash

set -e

DEFAULT_CONFIG_PREFIX="default"
BREW_CONFIG_PREFIX="brew"
CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

if [ $# -eq 0 ]; then
    # If no arguments provided, install default.conf.yaml
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${DEFAULT_CONFIG_PREFIX}${CONFIG_SUFFIX}"
else
    for conf in "$@"; do
        # Install configurations specified in command line arguments
        "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${conf}${CONFIG_SUFFIX}" --plugin-dir dotbot-brew
    done
fi
